{{- if .Values.notifications.outlook.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: outlook-email-templates
  namespace: {{ .Values.namespace }}
data:
  # Critical Alert Email Template
  critical-template.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
            .container { max-width: 600px; margin: 0 auto; background-color: white; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
            .header { background: linear-gradient(135deg, #ff4757, #ff6b7a); color: white; padding: 20px; border-radius: 8px 8px 0 0; text-align: center; }
            .content { padding: 20px; }
            .alert-box { background-color: #fff5f5; border-left: 4px solid #ff4757; padding: 15px; margin: 15px 0; border-radius: 4px; }
            .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin: 15px 0; }
            .info-item { background-color: #f8f9fa; padding: 10px; border-radius: 4px; }
            .label { font-weight: bold; color: #2c3e50; }
            .value { color: #34495e; margin-top: 5px; }
            .footer { background-color: #ecf0f1; padding: 15px; border-radius: 0 0 8px 8px; text-align: center; color: #7f8c8d; font-size: 12px; }
            .btn { display: inline-block; background: linear-gradient(135deg, #3742fa, #5352ed); color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin: 10px 5px; }
            .priority-critical { color: #ff4757; font-weight: bold; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🔥 CRITICAL INFRASTRUCTURE ALERT</h1>
                <p>Immediate attention required</p>
            </div>

            <div class="content">
                {{/* This will be populated by AlertManager template */}}
                {{ range .Alerts }}
                <div class="alert-box">
                    <h3>{{ .Annotations.summary }}</h3>
                    <p><strong>Description:</strong> {{ .Annotations.description }}</p>

                    <div class="info-grid">
                        <div class="info-item">
                            <div class="label">Instance</div>
                            <div class="value">{{ .Labels.instance }}</div>
                        </div>
                        <div class="info-item">
                            <div class="label">Namespace</div>
                            <div class="value">{{ .Labels.namespace }}</div>
                        </div>
                        <div class="info-item">
                            <div class="label">Severity</div>
                            <div class="value priority-critical">{{ .Labels.severity | upper }}</div>
                        </div>
                        <div class="info-item">
                            <div class="label">Started At</div>
                            <div class="value">{{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}</div>
                        </div>
                    </div>
                </div>
                {{ end }}

                <div style="text-align: center; margin: 20px 0;">
                    <a href="http://{{ $.Values.notifications.grafana_url }}" class="btn">📊 Open Grafana Dashboard</a>
                    <a href="http://{{ $.Values.notifications.prometheus_url }}" class="btn">🔍 Open Prometheus</a>
                </div>
            </div>

            <div class="footer">
                <p>This alert was automatically generated by the Observability Suite</p>
                <p>For support, contact: {{ $.Values.notifications.outlook.support_email | default "support@yourcompany.com" }}</p>
            </div>
        </div>
    </body>
    </html>

  # Warning Alert Email Template
  warning-template.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
            .container { max-width: 600px; margin: 0 auto; background-color: white; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
            .header { background: linear-gradient(135deg, #ffa502, #ff7675); color: white; padding: 20px; border-radius: 8px 8px 0 0; text-align: center; }
            .content { padding: 20px; }
            .alert-box { background-color: #fff8e1; border-left: 4px solid #ffa502; padding: 15px; margin: 15px 0; border-radius: 4px; }
            .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin: 15px 0; }
            .info-item { background-color: #f8f9fa; padding: 10px; border-radius: 4px; }
            .label { font-weight: bold; color: #2c3e50; }
            .value { color: #34495e; margin-top: 5px; }
            .footer { background-color: #ecf0f1; padding: 15px; border-radius: 0 0 8px 8px; text-align: center; color: #7f8c8d; font-size: 12px; }
            .btn { display: inline-block; background: linear-gradient(135deg, #3742fa, #5352ed); color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin: 10px 5px; }
            .priority-warning { color: #ffa502; font-weight: bold; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>⚠️ WARNING ALERT</h1>
                <p>Attention required</p>
            </div>

            <div class="content">
                {{ range .Alerts }}
                <div class="alert-box">
                    <h3>{{ .Annotations.summary }}</h3>
                    <p><strong>Description:</strong> {{ .Annotations.description }}</p>

                    <div class="info-grid">
                        <div class="info-item">
                            <div class="label">Instance</div>
                            <div class="value">{{ .Labels.instance }}</div>
                        </div>
                        <div class="info-item">
                            <div class="label">Severity</div>
                            <div class="value priority-warning">{{ .Labels.severity | upper }}</div>
                        </div>
                        <div class="info-item">
                            <div class="label">Started At</div>
                            <div class="value">{{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}</div>
                        </div>
                        <div class="info-item">
                            <div class="label">Status</div>
                            <div class="value">{{ .Status }}</div>
                        </div>
                    </div>
                </div>
                {{ end }}

                <div style="text-align: center; margin: 20px 0;">
                    <a href="http://{{ $.Values.notifications.grafana_url }}" class="btn">📊 Dashboard</a>
                </div>
            </div>

            <div class="footer">
                <p>Observability Suite - Warning Alert</p>
            </div>
        </div>
    </body>
    </html>

---
apiVersion: v1
kind: Secret
metadata:
  name: outlook-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  smtp_username: {{ .Values.notifications.outlook.smtp.username | b64enc }}
  smtp_password: {{ .Values.notifications.outlook.smtp.password | b64enc }}

---
# Outlook SMTP Configuration for AlertManager
apiVersion: v1
kind: ConfigMap
metadata:
  name: outlook-smtp-config
  namespace: {{ .Values.namespace }}
data:
  smtp-config.yml: |
    # Outlook/Office 365 SMTP Settings
    smtp_smarthost: '{{ .Values.notifications.outlook.smtp.server | default "smtp.office365.com:587" }}'
    smtp_from: '{{ .Values.notifications.outlook.smtp.from_email }}'
    smtp_auth_username: '{{ .Values.notifications.outlook.smtp.username }}'
    smtp_require_tls: {{ .Values.notifications.outlook.smtp.require_tls | default true }}

    # Email Recipients Configuration
    recipients:
      critical:
        primary: '{{ .Values.notifications.outlook.recipients.critical.primary }}'
        cc: '{{ .Values.notifications.outlook.recipients.critical.cc | default "" }}'
      warning:
        primary: '{{ .Values.notifications.outlook.recipients.warning.primary }}'
        cc: '{{ .Values.notifications.outlook.recipients.warning.cc | default "" }}'
      info:
        primary: '{{ .Values.notifications.outlook.recipients.info.primary }}'
{{- end }}