apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: blackbox-exporter
  ports:
    - name: http
      port: 9115
      targetPort: 9115
      {{- if eq .Values.blackboxExporter.service.type "NodePort" }}
      nodePort: 30115
      {{- end }}
  type: {{ .Values.blackboxExporter.service.type | default "ClusterIP" }}