apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      {{- if eq .Values.loki.service.type "NodePort" }}
      nodePort: 30310
      {{- end }}
  type: {{ .Values.loki.service.type | default "ClusterIP" }}