apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: {{ .Values.namespace }}
  labels:
    app: tempo
spec:
  replicas: {{ .Values.tempo.replicas }}
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: {{ .Values.tempo.image }}
        args:
        - -config.file=/etc/tempo/tempo.yaml
        ports:
        - containerPort: 3200
          name: http
        - containerPort: 9095
          name: grpc
        - containerPort: 14268
          name: jaeger-http
        - containerPort: 14250
          name: jaeger-grpc
        - containerPort: 9411
          name: zipkin
        resources:
          limits:
            cpu: {{ .Values.tempo.resources.limits.cpu }}
            memory: {{ .Values.tempo.resources.limits.memory }}
          requests:
            cpu: {{ .Values.tempo.resources.requests.cpu }}
            memory: {{ .Values.tempo.resources.requests.memory }}
        volumeMounts:
        - name: tempo-config
          mountPath: /etc/tempo
        - name: tempo-storage
          mountPath: /var/tempo
      volumes:
      - name: tempo-config
        configMap:
          name: tempo-config
      - name: tempo-storage
        persistentVolumeClaim:
          claimName: tempo-pvc