apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: ao
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      nodeSelector:
        kubernetes.io/hostname: uta-k8s-ao-01  # Deploy on AO node
      containers:
      - name: grafana
        image: grafana/grafana:10.1.5
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
          - mountPath: /etc/grafana/grafana.ini
            name: grafana-config
            subPath: grafana.ini
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin123
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          httpGet:
            httpHeaders:
            - name: Accept
              value: text/html
            path: /api/health
            port: 3000
            scheme: HTTP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Accept
              value: text/html
            path: /api/health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
        - name: grafana-config
          configMap:
              name: grafana-config

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ao
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30300
  selector:
    app: grafana