apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: ao
data:
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": []
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: ao
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    root_url = http://localhost:3000
    [security]
    admin_user = admin
    admin_password = admin123