apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: app-test
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: python:3.11-slim
        command:
        - sh
        - -c
        - |
          pip install flask==2.3.3 gunicorn==21.2.0
          python -c "
          from flask import Flask, jsonify
          import time, random, logging
          logging.basicConfig(level=logging.INFO)
          logger = logging.getLogger(__name__)
          app = Flask(__name__)

          def simulate_database_call():
              time.sleep(random.uniform(0.01, 0.05))
              return {'data': f'record_{random.randint(1000, 9999)}'}

          @app.route('/')
          def home():
              logger.info('Home endpoint accessed')
              db_data = simulate_database_call()
              return jsonify({'service': 'sample-app', 'status': 'running', 'version': '1.0.0', 'data': db_data, 'message': 'Simple Flask app before instrumentation'})

          @app.route('/healthz')
          def health():
              return jsonify({'status': 'healthy'})

          @app.route('/api/users')
          def get_users():
              logger.info('Getting users')
              db_data = simulate_database_call()
              users = [{'id': 1, 'name': 'John Doe'}, {'id': 2, 'name': 'Jane Smith'}]
              return jsonify({'users': users, 'metadata': db_data})

          if __name__ == '__main__':
              app.run(host='0.0.0.0', port=5000, debug=True)
          "
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: app-test
spec:
  selector:
    app: sample-app
  ports:
  - port: 8080
    targetPort: 5000
    nodePort: 30080
  type: NodePort