apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    meta.helm.sh/release-name: cxtm-internal
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-04-11T12:50:58Z"
  generation: 4
  labels:
    app.kubernetes.io/instance: cxtm-internal
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cxtm-notifications
    helm.sh/chart: cxtm-notifications-0.1.0
  name: cxtm-notifications
  namespace: default
  resourceVersion: "23689476"
  uid: 97c2127d-9279-4239-bf1c-5f4365563877
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: cxtm-internal
      app.kubernetes.io/name: cxtm-notifications
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: cxtm-internal
        app.kubernetes.io/name: cxtm-notifications
    spec:
      containers:
      - env:
        - name: SPARK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              key: spark-bot-token
              name: spark
        - name: SA_KEY
          valueFrom:
            secretKeyRef:
              key: sa-key
              name: service-account-api-key
        - name: PYTHONUNBUFFERED
          value: "0"
        - name: SMTP_SERVER
          value: outbound.cisco.com
        - name: SMTP_FROM_EMAIL
          value: noreply@cxtm.cisco.com
        - name: APP_SETTINGS_CACHE_TIME
          value: "60"
        - name: APP_SETTINGS_WHITELIST
          value: GLOBAL_MAX_RUNTIME,SMTP_SERVER,SMTP_FROM_EMAIL,TASK_STATE_EXPIRE_SECONDS,REMOVE_STOPPED_CONTAINERS,USE_ADDITIONAL_VOLUMES,ENFORCE_KNOWN_IMAGES
        - name: APP_SETTINGS_SECRET_WHITELIST
          value: CDETS_CONSUMER_KEY,CDETS_CONSUMER_SECRET,CDETS_ACCESS_TOKEN
        - name: TM2_BASE
          value: http://cxtm-internal-web:8080
        image: dockerhub.cisco.com/cx-svs-internal-docker/tm_notifications:25.3.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cxtm-notifications
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9200
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        cx-tm.cisco.com: app
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-04-11T12:51:48Z"
    lastUpdateTime: "2025-04-11T12:51:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-11T12:50:58Z"
    lastUpdateTime: "2025-04-28T19:04:06Z"
    message: ReplicaSet "cxtm-notifications-5756cb9dc9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
