apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-config.yaml: |
    receivers:
      # OTLP receiver for application traces and metrics
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      
      # Host metrics
      hostmetrics:
        collection_interval: 10s
        scrapers:
          cpu:
          disk:
          filesystem:
          memory:
          network:
      
      # Kubernetes cluster receiver
      k8s_cluster:
        collection_interval: 10s
        
      # Kubelet stats receiver  
      kubeletstats:
        collection_interval: 10s
        auth_type: "serviceAccount"
        endpoint: "https://${env:KUBE_NODE_NAME}:10250"
        insecure_skip_verify: true

    processors:
      # Batch processor for performance
      batch:
        timeout: 1s
        send_batch_size: 1024
        
      # Resource detection processor
      resource:
        attributes:
        - key: k8s.cluster.name
          value: cxtm-dev-cluster
          action: insert
        - key: deployment.environment  
          value: development
          action: insert
          
      # Memory limiter with required check_interval
      memory_limiter:
        limit_mib: 512
        check_interval: 1s

    exporters:
      # Splunk APM/Observability Cloud exporter
      sapm:
        access_token: "oksFxD-9HYcsCHBqvvh9mg"
        endpoint: "https://ingest.us1.signalfx.com/v2/trace"
        
      # Splunk HEC for logs
      splunk_hec:
        token: "oksFxD-9HYcsCHBqvvh9mg" 
        endpoint: "https://ingest.us1.signalfx.com/v1/log"
        source: "otel"
        sourcetype: "_json"
        
      # SignalFx exporter for metrics
      signalfx:
        access_token: "oksFxD-9HYcsCHBqvvh9mg"
        realm: "us1"

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, resource, batch]
          exporters: [sapm]
          
        metrics:
          receivers: [otlp, hostmetrics, k8s_cluster, kubeletstats]
          processors: [memory_limiter, resource, batch]
          exporters: [signalfx]
          
        logs:
          receivers: [otlp]
          processors: [memory_limiter, resource, batch] 
          exporters: [splunk_hec]
