# Patch to add OpenTelemetry init container to CXTM Scheduler
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cxtm-scheduler
  namespace: default
spec:
  template:
    spec:
      initContainers:
      - name: otel-auto-instrumentation-installer
        image: python:3.8-slim
        command: ["/bin/bash", "/scripts/install-otel.sh"]
        volumeMounts:
        - name: otel-auto-instrumentation
          mountPath: /otel-auto-instrumentation
        - name: otel-installation-scripts  
          mountPath: /scripts
        env:
        - name: PIP_CACHE_DIR
          value: /tmp/pip-cache
      containers:
      - name: scheduler
        # Add volume mount for OpenTelemetry packages
        volumeMounts:
        - name: otel-auto-instrumentation
          mountPath: /otel-auto-instrumentation
        env:
        # Keep existing OpenTelemetry environment variables
        - name: OTEL_SERVICE_NAME
          value: "cxtm-scheduler"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT  
          value: "http://otel-collector:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=development,k8s.cluster.name=cxtm-dev,k8s.namespace.name=default,service.name=cxtm-scheduler"
        # Add Python path for OpenTelemetry packages
        - name: PYTHONPATH
          value: "/otel-auto-instrumentation:$PYTHONPATH"
        - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
          value: "true"
        # Override the command to use auto-instrumentation
        command: ["/otel-auto-instrumentation/otel-instrument.sh"]
        # Keep original args (if any) - will need to check the original deployment
        # args: ["original-command-here"]
      volumes:
      - name: otel-auto-instrumentation
        emptyDir: {}
      - name: otel-installation-scripts
        configMap:
          name: otel-auto-instrumentation-init
          defaultMode: 0755
