apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: {{ .Values.namespace }}
  labels:
    app: cadvisor
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: cadvisor
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    {{- if eq .Values.cadvisor.service.type "NodePort" }}
    nodePort: 30080
    {{- end }}
  type: {{ .Values.cadvisor.service.type | default "ClusterIP" }}