{{- if .Values.alertmanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ .Values.environment.namespace | default .Values.namespace }}
  labels:
    app: alertmanager
    component: alert-management
spec:
  selector:
    app: alertmanager
  ports:
  - name: http
    port: 9093
    targetPort: 9093
    protocol: TCP
  - name: cluster
    port: 9094
    targetPort: 9094
    protocol: TCP
  type: ClusterIP
{{- end }}