{{- if .Values.alertmanager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: {{ .Values.environment.namespace | default .Values.namespace }}
  labels:
    app: alertmanager
    component: alert-management
spec:
  replicas: {{ .Values.alertmanager.replicas }}
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
        component: alert-management
    spec:
      {{- if .Values.environment.cluster.nodeSelector.enabled }}
      {{- if eq .Values.environment.cluster.nodeSelector.strategy "labels" }}
      nodeSelector:
        {{- toYaml .Values.environment.cluster.nodeSelector.nodeLabels | nindent 8 }}
      {{- else if eq .Values.environment.cluster.nodeSelector.strategy "hostname" }}
      {{- if .Values.environment.cluster.nodeSelector.targetNodes }}
      nodeSelector:
        kubernetes.io/hostname: {{ index .Values.environment.cluster.nodeSelector.targetNodes 0 }}
      {{- end }}
      {{- end }}
      {{- end }}
      containers:
      - name: alertmanager
        image: {{ .Values.alertmanager.image }}
        ports:
        - containerPort: 9093
          name: http
        resources:
          limits:
            cpu: {{ index .Values.resources.templates .Values.resources.sizing "cpu" "limits" }}
            memory: {{ index .Values.resources.templates .Values.resources.sizing "memory" "limits" }}
          requests:
            cpu: {{ index .Values.resources.templates .Values.resources.sizing "cpu" "requests" }}
            memory: {{ index .Values.resources.templates .Values.resources.sizing "memory" "requests" }}
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager
        - name: alertmanager-storage
          mountPath: /alertmanager
        args:
          - --config.file=/etc/alertmanager/alertmanager.yml
          - --storage.path=/alertmanager
          - --web.external-url=http://alertmanager:9093
          - --cluster.listen-address=0.0.0.0:9094
          - --log.level=info
        env:
        - name: CLUSTER_NAME
          value: {{ .Values.environment.name }}
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9093
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9093
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager-config
      - name: alertmanager-storage
        {{- if .Values.environment.cluster.storage.persistence.enabled }}
        persistentVolumeClaim:
          claimName: alertmanager-storage-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}