apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: {{ .Values.environment.namespace | default .Values.namespace }}
spec:
  selector:
    app: blackbox-exporter
  ports:
    - name: http
      port: 9115
      targetPort: 9115
  type: ClusterIP