apiVersion: v1
kind: ServiceAccount
metadata:
  name: cadvisor
  namespace: {{ .Values.namespace }}
  labels:
    app: cadvisor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cadvisor
  labels:
    app: cadvisor
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/stats", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cadvisor
  labels:
    app: cadvisor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cadvisor
subjects:
- kind: ServiceAccount
  name: cadvisor
  namespace: {{ .Values.namespace }}