apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      {{- if eq .Values.grafana.service.type "NodePort" }}
      nodePort: 30300
      {{- end }}
  type: {{ .Values.grafana.service.type | default "ClusterIP" }}