apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 472
        runAsGroup: 472
        fsGroup: 472
        runAsNonRoot: true
      containers:
      - name: grafana
        image: {{ .Values.grafana.image }}
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: {{ .Values.grafana.adminPassword }}
{{- if .Values.notifications.grafana_alerting.enabled }}
        # Enable Grafana Alerting
        - name: GF_ALERTING_ENABLED
          value: "true"
        - name: GF_UNIFIED_ALERTING_ENABLED
          value: "true"
        - name: GF_ALERTING_EXECUTE_ALERTS
          value: "true"
        # SMTP disabled - no email notifications
{{- end }}
        resources:
          limits:
            cpu: {{ .Values.grafana.resources.limits.cpu }}
            memory: {{ .Values.grafana.resources.limits.memory }}
          requests:
            cpu: {{ .Values.grafana.resources.requests.cpu }}
            memory: {{ .Values.grafana.resources.requests.memory }}
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
{{- if .Values.notifications.grafana_alerting.enabled }}
        # Alerting provisioning mounts
        - name: grafana-alerting-contactpoints
          mountPath: /etc/grafana/provisioning/alerting/contactpoints.yaml
          subPath: contactpoints.yaml
        - name: grafana-alerting-policies
          mountPath: /etc/grafana/provisioning/alerting/policies.yaml
          subPath: policies.yaml
        - name: grafana-alert-rules
          mountPath: /etc/grafana/provisioning/alerting/rules.yaml
          subPath: rules.yaml
{{- end }}
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
{{- if .Values.notifications.grafana_alerting.enabled }}
      # Alerting provisioning volumes
      - name: grafana-alerting-contactpoints
        configMap:
          name: grafana-alerting-provisioning
      - name: grafana-alerting-policies
        configMap:
          name: grafana-alerting-provisioning
      - name: grafana-alert-rules
        configMap:
          name: grafana-alert-rules
{{- end }}