apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: {{ .Values.environment.namespace | default .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.storage.size | default "10Gi" }}
  {{- if .Values.grafana.storage.storageClass }}
  storageClassName: {{ .Values.grafana.storage.storageClass }}
  {{- end }}