apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Values.environment.namespace | default .Values.namespace }}
spec:
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
  type: ClusterIP