{{- if .Values.mtr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mtr-analyzer
  namespace: {{ .Values.environment.namespace | default .Values.namespace }}
  labels:
    app: mtr-analyzer
    component: network-path-analysis
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: mtr-analyzer
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
{{- end }}