{{- if .Values.tempo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: {{ .Values.environment.namespace | default .Values.namespace }}
  labels:
    app: tempo
    component: tracing-backend
spec:
  selector:
    app: tempo
  ports:
  - name: http
    port: {{ .Values.tempo.service.port }}
    targetPort: 3200
    protocol: TCP
  - name: grpc
    port: 9095
    targetPort: 9095
    protocol: TCP
  - name: jaeger-http
    port: 14268
    targetPort: 14268
    protocol: TCP
  - name: jaeger-grpc  
    port: 14250
    targetPort: 14250
    protocol: TCP
  - name: zipkin
    port: 9411
    targetPort: 9411
    protocol: TCP
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
  type: {{ .Values.tempo.service.type }}
{{- end }}