# Splunk OpenTelemetry Collector Configuration
# This file tells Helm how to configure the OTEL collector

# Splunk connection settings
splunkObservability:
  accessToken: "oksFxD-9HYcsCHBqvwh9mg"
  realm: "us1"
  metricsEnabled: true
  tracesEnabled: true
  logsEnabled: true
  profilingEnabled: true

# Cluster name
clusterName: "uta-k8s-cxtm-cluster"
environment: "production"

# OpenTelemetry Operator - runs on AO nodes only
operator:
  enabled: true
  nodeSelector:
    ao-node: observability

# Install operator components
operatorcrds:
  install: true

# OTEL Agent - runs on ALL nodes to collect data
agent:
  enabled: true
  hostNetwork: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

# Cluster receiver - runs on AO nodes only
clusterReceiver:
  enabled: true
  nodeSelector:
    ao-node: observability
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Disable gateway mode
gateway:
  enabled: false

# Auto-detect services
autodetect:
  prometheus: true
  istio: false

# Use OTEL for logs
logsEngine: otel
logsCollection:
  containers:
    enabled: true
  extraFileLogs: {}