apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      {{- if eq .Values.prometheus.service.type "NodePort" }}
      nodePort: 30090
      {{- end }}
  type: {{ .Values.prometheus.service.type | default "ClusterIP" }}