apiVersion: apps/v1
kind: Deployment
metadata:
  name: smokeping
  namespace: {{ .Values.namespace }}
  labels:
    app: smokeping
spec:
  replicas: {{ .Values.smokeping.replicas }}
  selector:
    matchLabels:
      app: smokeping
  template:
    metadata:
      labels:
        app: smokeping
    spec:
      containers:
      - name: smokeping
        image: {{ .Values.smokeping.image }}
        ports:
        - containerPort: 80
          name: http
        env:
        - name: TZ
          value: "UTC"
        resources:
          limits:
            cpu: {{ .Values.smokeping.resources.limits.cpu }}
            memory: {{ .Values.smokeping.resources.limits.memory }}
          requests:
            cpu: {{ .Values.smokeping.resources.requests.cpu }}
            memory: {{ .Values.smokeping.resources.requests.memory }}
        volumeMounts:
        - name: smokeping-config
          mountPath: /config
        - name: smokeping-data
          mountPath: /data
      volumes:
      - name: smokeping-config
        configMap:
          name: smokeping-config
      - name: smokeping-data
        persistentVolumeClaim:
          claimName: smokeping-pvc