apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smokeping-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.smokeping.storage.size }}
  {{- if .Values.smokeping.storage.storageClass }}
  storageClassName: {{ .Values.smokeping.storage.storageClass }}
  {{- end }}